version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  main:
    jobs:
      - test
